name: iOS Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0' # Specify the Xcode version you need
    - name: Install dependencies
      run: swift package resolve
    - name: Build
      run: xcodebuild -scheme iOS_SideMenu_Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' build
    - name: Run tests
      run: xcodebuild test -scheme iOS_SideMenu_Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0'
